2023 LBNL update
deployment-gap-model-education-fund/deployment-gap-model pull request #331
Opened 2024-05-02 17:38 UTC by bendnorman

2024-05-14 19:00 UTC, bendnorman commented on src/dbcp/data_mart/projects.py
> +GS_REGIONS = ("MISO", "NYISO", "ISONE", "PJM", "ERCOT", "SPP")
Using LBNL for CAISO now because of data sourcing issues with GS.

2024-05-14 19:01 UTC, bendnorman commented on src/dbcp/etl.py
> +    lbnl_uri = "gs://dgm-archive/lbnl_iso_queue/queues_2023_clean_data.xlsx"
Using the `gs://dgm-archive` bucket instead of github for consistency. Planning on migrating everything from github to this bucket at some point.

2024-05-14 19:02 UTC, bendnorman commented on src/dbcp/transform/gridstatus.py
> +    projects = pd.concat(projects)
Renaming this variable because it contains withdrawn and operational projects.

2024-05-14 19:03 UTC, bendnorman commented on src/dbcp/transform/lbnl_iso_queue.py
> +            "queue_status",
I added `queue_status` to the deduplication key now that we have operational and withdrawn projects.

2024-05-20 12:03 UTC, TrentonBush requested changes
A couple of minor questions, but otherwise looks good! Thanks Ben

2024-05-20 12:03 UTC, TrentonBush commented on src/dbcp/validation/tests.py
> +        notnull.any(axis=1).sum() == 2423
I ran this locally and it wanted 2424 places. But it could be a cache thing. I guess the GH Action will check for us (it has no cache, right?)

2024-05-20 21:25 UTC, TrentonBush approved these changes

2024-05-20 21:25 UTC, merged